fix: eindstatus duplicate check used less precise zaak einddatum instead of eindstatus datumstatusgezet resulting in duplicate check false positives
wearefrank/zaakbrug pull request #267
Opened 2024-01-30 13:14 UTC by DelanoWAF

Incorrect XSLT condition caused loss of datetime information. Resolved now by replacing the condition in question.

Resolves #262

2024-01-31 13:07 UTC, MLenterman requested changes
Im missing the correction on the testcase.

2024-01-31 13:07 UTC, MLenterman commented on src/main/configurations/Translate/Zgw/Zaken/Model/ZgwStatus.xslt
> +            </xsl:when>
This is doing the same thing as the "otherwise", so this one is not needed.

2024-01-31 14:12 UTC, DelanoWAF commented
Performing additional investigation into the safeguard that prevents duplicate results. It appears to be incorrect still and requires adjustment.

2024-02-01 13:44 UTC, DelanoWAF commented
Delays in test cases are necessary. The code still checks the datetime of statusDatumGezet to ensure that no two statuses were set at the exact same time. However, the safeguard for status type has been added to prevent a status from being added to a case more than once. 

Original code did include a minor version of the safeguard but this appeared to not enough, as well as not functioning correctly.

2024-02-12 11:43 UTC, MLenterman approved these changes

2024-02-12 11:46 UTC, MLenterman approved these changes

2024-02-12 11:51 UTC, merged

2024-02-12 11:57 UTC, MLenterman commented
:tada: This PR is included in version 1.15.9 :tada:

The release is available on [GitHub release](https://github.com/wearefrank/zaakbrug/releases/tag/v1.15.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: